this.dir <- dirname(parent.frame(2)$ofile)
print(this.dir)

source(paste0(this.dir, "/test_case_1.R"))
source(paste0(this.dir, "/test_case_2.R"))
source(paste0(this.dir, "/test_case_3.R"))
source(paste0(this.dir, "/test_case_4.R"))
source(paste0(this.dir, "/test_case_5.R"))
source(paste0(this.dir, "/test_case_6.R"))
source(paste0(this.dir, "/test_case_7.R"))
source(paste0(this.dir, "/test_case_8.R"))
source(paste0(this.dir, "/test_case_9.R"))
source(paste0(this.dir, "/test_case_10.R"))
source(paste0(this.dir, "/test_case_11.R"))
source(paste0(this.dir, "/test_case_12.R"))
source(paste0(this.dir, "/test_case_13.R"))
