#need to change to pileline-latest  after testing
FROM pipeline-base:v2
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV CHOLERA_SKIP_STAN=TRUE
ENV PRODUCTION_RUN=FALSE
ENV IN_DOCKER=TRUE
ENV COVARIATE_DATABASE_PASSWORD=test

#For test remove later

# Create and set permissions
RUN useradd app && \
    mkdir -p /home/app/cholera-mapping-pipeline/Analysis && \
    mkdir /home/app/cholera-mapping-pipeline/Layers && \
    mkdir /home/app/cholera-mapping-pipeline/packages && \
    touch /home/app/cholera-mapping-pipeline/.choldir && \
    chown -R app:app /home/app && \
    adduser app staff

# Copy files into container
COPY Analysis /home/app/cholera-mapping-pipeline/Analysis/
COPY Layers/covariate_dictionary.yml  /home/app/cholera-mapping-pipeline/Layers/covariate_dictionary.yml
COPY packages  /home/app/cholera-mapping-pipeline/packages/

RUN chown -R app:app /home/app
# Install R packages
RUN R -e  "install.packages('/home/app/cholera-mapping-pipeline/packages/taxdat', type='source', repos=NULL)"
WORKDIR /home/app/cholera-mapping-pipeline
USER app
# when run docker mount folder to container and install taxdat in terminal
# Set default command
CMD ["R"]
