name: 'BEN_BFA_CIV_CMR_GHA_GIN_GMB_GNB_LBR_MLI_MRT_NER_NGA_SEN_SLE_TCD_TGO_2015_2019_20km'
countries: ['289','100','582','157','192','30','701','375','181','55','681','1045','36','141','604','145','453']
countries_name: ['BEN','BFA','CIV','CMR','GHA','GIN','GMB','GNB','LBR','MLI','MRT','NER','NGA','SEN','SLE','TCD','TGO']
aoi: 'raw'
res_space: 20
res_time: '1 years'
smoothing_period: 1
case_definition: 'suspected'
start_time: '2015-01-01'
end_time: '2019-12-31'
covariate_choices: ['dist_to_water','water_access','san_access']
data_source: 'sql'
ovrt_metadata_table: no
ingest_covariates: yes
ingest_new_covariates: no
covar_warmup: yes
censoring: no
aggregate: yes
time_effect: yes
time_effect_autocorr: no
beta_sigma_scale: 1
stan:
  ncores: 4
  model: 'update_yearly_dagar_timevary_speedup_flexible.stan'
  niter: 2000
  recompile: TRUE
