name: 'BGD_2014_2018_20km'
countries: 118 # The one that website uses
countries_name: 'BGD' # the one to print
aoi: 'raw'
res_space: 20
res_time: '1 month'
smoothing_period: 12
case_definition: 'suspected'
start_time: '2014-01-01'
end_time: '2018-12-31'
covariate_choices: ['dist_to_water','water_access']
data_source: 'sql'
ovrt_metadata_table: no
ingest_covariates: yes
ingest_new_covariates: no
covar_warmup: yes
censoring: yes
aggregate: yes
time_effect: yes
time_effect_autocorr: no
beta_sigma_scale: 1
stan:
  ncores: 4
  model: 'dagar_seasonal.stan'
  niter: 100
  recompile: TRUE
