smoothing_period: 
  abbreviation: sp
  definition:
  allowed_values:
covar_warmup: 
  abbreviation: cw
censoring: 
  abbreviation: cs
aggregate:
  abbreviation: ag
time_effect:
  abbreviation: te
time_effect_autocorr:
  abbreviation: tea
beta_sigma_scale:
  abbreviation: bs
sigma_eta_scale:
  abbreviation: es
tfrac_thresh:
  abbreviation: tft
set_tfrac:
  abbreviation: tfs