name: CMR
aoi: raw
countries: '157'
countries_name: CMR
start_time: '2015-01-01'
end_time: '2019-12-31'
res_time: 1 years
res_space: 20
smoothing_period: 1
case_definition: suspected
covariate_choices:
- dist_to_water
- water_access
- san_access
- open_defe
- stunting
- wasting
- access_cities
data_source: sql
ovrt_metadata_table: no
ingest_covariates: no
ingest_new_covariates: no
censoring: yes
aggregate: yes
time_effect: yes
time_effect_autocorr: no
use_weights: no
stan:
  ncores: 4
  model: update_yearly_dagar_timevary_speedup_flexible.stan
  niter: 2000
  recompile: yes
