---
title: ""
output: html_document
params:
  cholera_directory: "../../"
  config_directory: "../configs/2015_2019_full_base/"
  max_countries: Inf
---
```{r setup, include=FALSE, dev="CairoPNG"}
library(stringr)
library(dplyr)
library(magrittr)
library(purrr)
library(readr)
library(ggplot2)
library(kableExtra)
library(RColorBrewer)
library(MCMCvis)
library(sf)
library(abind)
library(taxdat)

knitr::opts_chunk$set(echo = FALSE,
 # dev.args = list(png = list(type = "cairo")),
  dev = "CairoPNG",
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  cache.lazy = F,
  error = TRUE,
  bitmapType = "cairo")


```

```{r datapull, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
all_configs <- list.files(params$config_directory,full.names=TRUE)
all_locations <- stringr::str_extract(all_configs, "[A-Z]{3}")
all_times <- unique(stringr::str_extract(all_configs, "[0-9]{4}_[0-9]{4}"))
if(length(all_times) > 1){
  stop("This report was not intended to compile runs from different time ranges")
}

sf_cases_resized <- list()
sf_grid <- list()
country_count <- 0
for(config_filename in all_configs){
  print(config_filename)
  if(country_count >= params$max_countries){break}
  config <- yaml::read_yaml(config_filename)
  file_names <- taxdat::get_filenames(config, params$cholera_directory)
  print(file_names)
  if(all(file.exists(file_names))){
    stan_input <- taxdat::read_file_of_type(file_names[['stan_input']], "stan_input")
    model.rand <- taxdat::read_file_of_type(file_names[['stan_output']], "model.rand")
    niter_per_chain <- dim(MCMCvis::MCMCchains(model.rand,params='lp__',chain_num=1))[1]
    nchain <- dim(MCMCvis::MCMCchains(model.rand,params='lp__'))[1] / niter_per_chain
    stan_output <- lapply(rstan::extract(model.rand), function(x){array(x,c(niter_per_chain, nchain, dim(x)[-1]))})

    
    stan_input$sf_grid <- stan_input$sf_grid %>% dplyr::ungroup() %>% dplyr::select(t,id)
    stan_input$sf_grid[paste('cases','chain',seq_len(nchain),sep='_')] <- apply(stan_output$grid_cases, c(3,2), mean)
    stan_input$sf_grid[paste('rate','chain',seq_len(nchain),sep='_')] <- apply(exp(stan_output$log_lambda), c(3,2), mean)
    stan_input$sf_grid$row_index <- seq_len(nrow(stan_input$sf_grid))
    stan_input$sf_grid <- tidyr::pivot_longer(
      stan_input$sf_grid,
      cols=c(
        paste('cases','chain',seq_len(nchain),sep='_'),
        paste('rate','chain',seq_len(nchain),sep='_')
      ),
      names_to="scenario",
      values_to="modeled"
    ) %>% sf::st_sf()
    stan_input$sf_grid <- tidyr::separate(col=scenario, into = c('type',NA,'chain'),stan_input$sf_grid)
  
    stan_input$sf_cases_resized <- dplyr::rename(
      dplyr::select(sf::st_as_sf(dplyr::ungroup(stan_input$sf_cases_resized)), locationPeriod_id, OC_UID,TL,TR,attributes.fields.suspected_cases),
      observed = attributes.fields.suspected_cases
    )
    # stan_input$sf_cases_resized$modeled_cases <- apply(stan_output$modeled_cases,3,mean)
    stan_input$sf_cases_resized[paste('cases','chain',seq_len(nchain),sep='_')] <- apply(stan_output$modeled_cases, c(3,2), mean)
    stan_input$sf_cases_resized$row_index <- seq_len(nrow(stan_input$sf_cases_resized))
    stan_input$sf_cases_resized <- tidyr::pivot_longer(stan_input$sf_cases_resized,cols=paste('cases','chain',seq_len(nchain),sep='_'),names_to="scenario",values_to="modeled") %>% sf::st_sf()
    stan_input$sf_cases_resized <- tidyr::separate(col=scenario, into = c('type',NA,'chain'),stan_input$sf_cases_resized)

    stan_input$sf_cases_resized$filename <- config_filename
    stan_input$sf_grid$filename <- config_filename
  
    if("list" %in% class(sf_grid)){
      sf_grid <- stan_input$sf_grid
    } else {
      sf_grid <- rbind(sf_grid, stan_input$sf_grid)
    }
    if("list" %in% class(sf_cases_resized)){
      sf_cases_resized <- stan_input$sf_cases_resized
    } else {
      sf_cases_resized <- rbind(sf_cases_resized, stan_input$sf_cases_resized)
    }

    country_count <- country_count + 1
  }
}

afr_shp <- sf::st_boundary(sf::st_read(paste(params$cholera_directory,"Layers/Africa.shp",sep='/')))

# disjoint_set_sf_cases_observed <- get_disjoint_set_sf_cases(dplyr::mutate(sf_cases_resized,attributes.fields.suspected_cases = observed_cases))
# disjoint_set_sf_cases_modeled <- get_disjoint_set_sf_cases(dplyr::mutate(sf_cases_resized,attributes.fields.suspected_cases = modeled_cases))
# if(!all(disjoint_set_sf_cases_observed$attributes.location_period_id == disjoint_set_sf_cases_modeled$attributes.location_period_id,na.rm=TRUE)){
#   stop("Expected disjoint_set_sf_cases to be in the same order")
# }
# if(!all(disjoint_set_sf_cases_observed$set == disjoint_set_sf_cases_modeled$set,na.rm=TRUE)){
#   stop("Expected disjoint_set_sf_cases to have the same sets")
# }
# disjoint_set_sf_cases <- disjoint_set_sf_cases_observed[,c("set","attributes.location_period_id")]
# 
# disjoint_set_sf_cases$observed_cases <- disjoint_set_sf_cases_observed$cases
# disjoint_set_sf_cases$observed_area_adjusted_cases <- disjoint_set_sf_cases_observed$area_adjusted_cases
# disjoint_set_sf_cases$observed_variance <- disjoint_set_sf_cases_observed$variance
# disjoint_set_sf_cases$observed_number_observations <- disjoint_set_sf_cases_observed$observations
# 
# disjoint_set_sf_cases$modeled_cases <- disjoint_set_sf_cases_modeled$cases
# disjoint_set_sf_cases$modeled_area_adjusted_cases <- disjoint_set_sf_cases_modeled$area_adjusted_cases
# disjoint_set_sf_cases$modeled_variance <- disjoint_set_sf_cases_modeled$variance
# disjoint_set_sf_cases$modeled_number_observations <- disjoint_set_sf_cases_modeled$observations
# disjoint_set_sf_cases$error_cases <- (disjoint_set_sf_cases$modeled_cases - disjoint_set_sf_cases$observed_cases)
```

# Mapping results summary for `r paste(all_locations, collapse =', ')` and period `r all_times`

```{r makenosplit, echo=FALSE, warning=FALSE,message=FALSE}
single_sf_grid <- sf_grid %>% dplyr::group_by(id, type) %>% dplyr::summarize(modeled = mean(modeled), geometry = unique(geom)) %>% dplyr::ungroup()
```

```{r gridoutcase, fig.cap="Plot Grid Output Cases", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(single_sf_grid,type=='cases'),"modeled", facet_column='type', colorscale_type = 'cases', render=TRUE, plot_border = afr_shp)
```

```{r gridoutrate, fig.cap="Plot Grid Output Rates", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(single_sf_grid,type=='rate'),"modeled", facet_column='type', colorscale_type = 'rates', render=TRUE, plot_border = afr_shp)
```

```{r gridoutcaselog, fig.cap="Plot Grid Output Cases with log transform", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(single_sf_grid,type=='cases'),"modeled", facet_column='type', colorscale_type = 'cases', render=TRUE, plot_border = afr_shp, use_log=TRUE)
```

```{r gridoutratelog, fig.cap="Plot Grid Output Rates with log transform", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(single_sf_grid,type=='rate'),"modeled", facet_column='type', colorscale_type = 'rates', render=TRUE, plot_border = afr_shp, use_log=TRUE)
```

```{r makechainsplit, echo=FALSE, warning=FALSE,message=FALSE}
rm(single_sf_grid)
chain_sf_grid <- sf_grid %>% dplyr::group_by(id,chain,type) %>% dplyr::summarize(modeled = mean(modeled), geometry = unique(geom)) %>% dplyr::ungroup()
```

```{r chaingrdioutcase, fig.cap="Plot Grid Output Cases by chain", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(chain_sf_grid,type=='cases'), "modeled", "chain", colorscale_type = 'cases', render=TRUE, plot_border = afr_shp)
```

```{r chaingridoutrate, fig.cap="Plot Grid Output Rates by chain", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(chain_sf_grid,type=='rate'), "modeled", "chain", colorscale_type = 'rates', render=TRUE, plot_border = afr_shp)
```

```{r chaingridoutcaselog, fig.cap="Plot Grid Output Cases with log transform by chain", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(chain_sf_grid,type=='cases'), "modeled", "chain", colorscale_type = 'cases', render=TRUE, plot_border = afr_shp, use_log = TRUE)
```

```{r chaingridoutratelog, fig.caps = "Plot Grid Output Rates with log transform by chain", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(chain_sf_grid,type=='rate'), "modeled", "chain", colorscale_type = 'rates', render=TRUE, plot_border = afr_shp, use_log = TRUE)
```

```{r maketimesplit, echo=FALSE, warning=FALSE,message=FALSE}
rm(chain_sf_grid)
time_sf_grid <- sf_grid %>% dplyr::group_by(id,t,type) %>% dplyr::summarize(modeled = mean(modeled), geometry = unique(geom)) %>% dplyr::ungroup()
```

```{r timegrdioutcase, fig.cap="Plot Grid Output Cases by time", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(time_sf_grid,type=='cases'), "modeled", "t", colorscale_type = 'cases', render=TRUE, plot_border = afr_shp)
```

```{r timegridoutrate, fig.cap="Plot Grid Output Rates by time", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(time_sf_grid,type=='rate'), "modeled", "t", colorscale_type = 'rates', render=TRUE, plot_border = afr_shp)
```

```{r timegridoutcaselog, fig.cap="Plot Grid Output Cases with log transform by time", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(time_sf_grid,type=='cases'), "modeled", "t", colorscale_type = 'cases', render=TRUE, plot_border = afr_shp, use_log = TRUE)
```

```{r timegridoutratelog, fig.caps = "Plot Grid Output Rates with log transform by time", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
taxdat::plot_map(dplyr::filter(time_sf_grid,type=='rate'), "modeled", "t", colorscale_type = 'rates', render=TRUE, plot_border = afr_shp, use_log = TRUE)
```

```{r cleantimesplit, echo=FALSE, warning=FALSE,message=FALSE}
rm(time_sf_grid)
```

```{r obsin, fig.cap="Plot Observation Cases Input", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
# plot_cases(disjoint_set_sf_cases,"modeled""set", render=TRUE)
```

```{r obsout, fig.cap="Plot Observation Cases Output", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
# plot_cases(disjoint_set_sf_cases,"observed_cases","set", render=TRUE)
```

```{r obserr, fig.cap="Plot Observation Cases Error", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
# plot_cases(disjoint_set_sf_cases,"error_cases","set", render=TRUE)
```

```{r modelfit, fig.cap="Plot Observed vs Modeled", echo=FALSE, warning=FALSE,message=FALSE, fig.fullwidth=TRUE}
sf_cases_resized %>%
  ggplot2::ggplot() +
  ggplot2::geom_point(ggplot2::aes(x=modeled+1,y=observed+1,color=as.character(chain))) +
  ggplot2::scale_x_continuous(trans="log10") +
  ggplot2::scale_y_continuous(trans="log10")
```
