---
title: ""
output: html_document
params:
  cholera_directory: "../../"
  config: "../configs/2010_2014/config_KEN_2010_2014.yml"
---
```{r setup, include=FALSE, dev="CairoPNG"}
knitr::opts_chunk$set(inlude = FALSE, dev="CairoPNG")
library(stringr)
library(dplyr)
library(magrittr)
library(purrr)
library(readr)
library(ggplot2)
library(kableExtra)

source(str_c(params$cholera_directory, "/Analysis/output/model_run_report_helpers.R"))
source(str_c(params$cholera_directory,"/packages/taxdat/R/readData.R"))
```

# Mapping results summary for `r str_extract(params$config, "(?<=g_)[A-Z]{3}(?=_)")` and period `r str_extract(params$config, "(?<=_)[0-9]{4}_[0-9]{4}(?=\\.)")`

## Cholera input data
**Data input:**
```{r cases, echo=FALSE, message=FALSE, warning=FALSE}

# Load data directory
config <- yaml::read_yaml(params$config)

file_names <- getFilenames(config, params$cholera_directory)
# file_names <- gsub("data/", "data_marcc/", file_names)
preprocessed_data_filename = file_names["data"]
stan_inuput_filename = file_names["stan_input"]

sf_cases <- read_file_of_type(preprocessed_data_filename, "sf_cases")
sf_cases_resized <- read_file_of_type(stan_inuput_filename, "stan_input")$sf_cases_resized

# Get case data statistics
obs_stats <- get_obs_stats(sf_cases_resized)
dropped_obs <- sf_cases %>% filter(!(id %in% sf_cases_resized$id))
dropped_stats <- get_obs_stats(dropped_obs)

obs_stats %>% 
  select(-contains("u_")) %>% 
  mutate_if(is.numeric, function(x) {format(x , big.mark=",")}) %>% 
  kableExtra::kable(col.names = c("year", "# observations", "# suspected cases", "# location periods", "# observation collections")) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped")) %>%
  kableExtra::kable_paper(full_width = F) %>%
  kableExtra::row_spec(nrow(obs_stats), bold = T) 
```

**Data dropped:**

```{r dropcases, echo=FALSE, message=FALSE, warning=FALSE}
dropped_obs <- sf_cases %>% filter(!(id %in% sf_cases_resized$id))
dropped_stats <- get_obs_stats(dropped_obs)

dropped_stats %>% 
  mutate_if(is.numeric, function(x) {format(x , big.mark=",")}) %>% 
  kableExtra::kable(col.names = c("year", "# dropped observations", "# dropped suspected cases", "# dropped location periods",  "dropped location periods", "# dropped  observation collections",  "dropped observation collections")) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped")) %>%
  kableExtra::kable_paper(full_width = F) %>%
  kableExtra::row_spec(nrow(dropped_stats), bold = T) 
```

```{r disjoint set sf cases}
disjoint_set_sf_cases <- get_disjoint_set_sf_cases(file_names["data"])
```

```{r rawobsmap, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap="Observed case counts by time adjusted for time fraction cases/year"}
plot_raw_observed_cases(
  disjoint_set_sf_cases, 
  render = T
)
```
```{r areadjustedmap, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap="Area adjusted average observed case counts by time adjusted for time fraction cases/(year * kilometer)"}
disjoint_set_sf_cases <- get_disjoint_set_sf_cases(file_names["data"])
plot_area_adjusted_observed_cases(
  disjoint_set_sf_cases, 
  render = T
)
```

```{r obsmap, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap="Number of observations by unique observed location periods."}
disjoint_set_sf_cases <- get_disjoint_set_sf_cases(file_names["data"])
plot_raw_observations(disjoint_set_sf_cases, 
                      render = T)
```


## Covariates

### Population
```{r pop, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap="Population density"}
plot_raster_population(covar_data_filename = file_names["covar"], 
                       render = T)
```

### Other covariates

```{r covars, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=8, fig.cap="Covariate rasters"}
plot_raster_covariates(covar_data_filename = file_names["covar"], 
                       render = T)
```

## Output maps

```{r caserast, echo=FALSE, fig.cap="Modeled cases", fig.height=5, fig.width=10, message=FALSE, warning=FALSE}
case_raster <- get_case_raster(preprocessed_data_filename = file_names["data"],
                               covar_data_filename = file_names["covar"],
                               model_output_filenames = file_names["stan_output"])

plot_modeled_cases(case_raster, 
                   render = T)

```

```{r raterast, echo=FALSE, fig.cap="Modeled rates", fig.height=5, fig.width=10, message=FALSE, warning=FALSE}
plot_modeled_rates(case_raster, 
                   render = T)
```

## Validation
```{r datafidelity, echo=FALSE, fig.cap="Observations vs. modeled cases", fig.height=6, fig.width=6, message=FALSE, warning=FALSE}
data_fidelity <- get_data_fidelity(file_names["stan_output"])

plot_model_fidelity(data_fidelity = data_fidelity,
                    case_raster = case_raster, 
                    render = T)
```

```{r traceplots, echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.cap="Stan trace plots"}
model.rand <- read_file_of_type(filename = file_names["stan_output"],"model.rand")
rstan::traceplot(model.rand, pars =  c("rho", "betas", "log_std_dev_w"))
```



```{r params, echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, fig.width=6, fig.cap="Parameter posteriors"}
rstan::plot(model.rand, pars =  c("rho", "betas", "log_std_dev_w"))
```
```{r rhat, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap="Gelman-Rubin Rhat"}
plot_rhat(model.rand, render = T)
```



```{r WHO output, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap = "comparison with WHO Output"}
who_annual_cases <- sf_cases_resized
chains <- rstan::extract(model.rand)
who_annual_cases$modeled <- apply(chains$modeled_cases,2,mean)
who_annual_cases$observed <- who_annual_cases$attributes.fields.suspected_cases # fix me
who_annual_cases <- pull_output_by_source(who_annual_cases, "%WHO Annual Cholera Reports%")
who_annual_cases %>% 
  as.data.frame() %>%
  select(OC_UID, TL, TR, observed, modeled) %>% 
  mutate_if(is.numeric, function(x) {format(round(x) , big.mark=",")}) %>% 
  kableExtra::kable(col.names = c("OC id", "start time", "end time", "# Observed cases", "# Modeled Cases")) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped"))
```

```{r full country modeled cases, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=10, fig.cap = "comparison with WHO Output"}
grid_cases_mean <- apply(chains$grid_cases,2,mean)
total_cases <- sum(grid_cases_mean)
print(paste("There are",format(round(total_cases), big.mark=","),"total cases"))
```
