---
title: "Output Summary Report"
output: html_document
date: "`r lubridate::now()`"
params: 
  cholera_directory: "~/projects/cholera-mapping-pipeline"
  config: "Analysis/cholera-configs/production_tests/subgrid/BDI/config_BDI_2015_2019_censoring.yml"
---
```{r setup, include=FALSE, dev="CairoPNG",message=FALSE}
library(knitr)
knitr::opts_chunk$set(
  cache=FALSE,
  cache.lazy = FALSE,
  echo = FALSE,
  dev="CairoPNG",
  error = FALSE,
  fig.align = "center",
  message = TRUE,
  warning = TRUE
)
library(stringr)
library(dplyr)
library(magrittr)
library(purrr)
library(readr)
library(ggplot2)
library(kableExtra)
library(taxdat)
library(sf)
library(raster)
library(stars)
library(taxdat)
library(cmdstanr)
library(ggthemes)
library(ggrepel)
sf::sf_use_s2(FALSE)

### other new packages (mainly for "rgeoboundaries")
chooseCRANmirror(ind = 77)

package_list <- c(
  "fasterize", 
  "remotes",
  "rgeoboundaries"
)

for (package in package_list) {
  if (!require(package = package, character.only = T)) {
    if (package == "rgeoboundaries"){
      try({
        remotes::install_gitlab("dickoa/rgeoboundaries")
        remotes::install_github("wmgeolab/rgeoboundaries")
      })
    }else{
      install.packages(pkgs = package)
      library(package = package, character.only = T)
    }
  }
}

#Figure Caption Numbering,
capFigNo = 1
#Function to add the Figure Number
capFig = function(x){
  x = paste0("Figure ",capFigNo,". ",x)
  capFigNo <<- capFigNo + 1
  x
}

```

```{r load data, message=FALSE, warning=FALSE}

file_names <- taxdat::get_filenames(
  config = str_c(params$cholera_directory, params$config, sep = "/") %>% yaml::read_yaml(), 
  cholera_directory = params$cholera_directory)

load(file_names["data"])
load(file_names["stan_input"])

chol_gen <- readRDS(file_names["stan_genquant"])

```


# Outputs for `r stringr::str_extract(params$config, "[A-Z]{3}")` and period `r stringr::str_extract(params$config, "[0-9]{4}_[0-9]{4}")`


### Output shapefiles
**Shapefiles used for output summaries:**
```{r out-shape}
#| fig.height=5,
#| fig.width=10,
#| fig.cap=capFig("Shapefiles used for output summaries pulled form rgeoboundaries")
ggplot(output_shapefiles) +
  geom_sf() +
  ggrepel::geom_label_repel(
    aes(label = shapeName, geometry = geom),
    stat = "sf_coordinates",
    min.segment.length = 0,
    size = 2,
    max.overlaps = Inf,
    alpha = .8
  )  +
  facet_wrap(~admin_level) +
  theme_map()
```
```{r output}

# Get cases and rates summaries
cases <- chol_gen$summary(variables = "location_cases_output", 
                          c(posterior::default_summary_measures(),
                            posterior::default_convergence_measures()),
                          .cores = 4) %>% 
  mutate(id = str_extract(variable, "[0-9]+") %>% as.numeric(),
         location_period_id = stan_input$fake_output_obs$locationPeriod_id[id],
         TL = stan_input$fake_output_obs$TL[id])

rates <- chol_gen$summary(variables = "location_rates_output", 
                          c(posterior::default_summary_measures(),
                            posterior::default_convergence_measures()),
                          .cores = 4) %>% 
  mutate(id = str_extract(variable, "[0-9]+") %>% as.numeric(),
         location_period_id = stan_input$fake_output_obs$locationPeriod_id[id],
         TL = stan_input$fake_output_obs$TL[id])

output_data <- output_shapefiles %>% 
  inner_join(cases %>% dplyr::select(cases = mean, 
                                     cases_q5 = q5,
                                     cases_q95 = q95,
                                     location_period_id, TL)) %>% 
  inner_join(rates %>% dplyr::select(rate = mean, 
                                     rate_q5 = q5,
                                     rate_q95 = q95,
                                     location_period_id, TL))

# Data over whole period

# Sum of cases by location for whole period
tot_cases <- chol_gen$summary(variables = "location_total_cases_output", 
                              c(posterior::default_summary_measures(),
                                posterior::default_convergence_measures()),
                              .cores = 4) %>% 
  mutate(id = str_extract(variable, "[0-9]+") %>% as.numeric(),
         location_period_id = output_shapefiles$location_period_id[id],
         shapeName = output_shapefiles$shapeName[id],
         admin_level = output_shapefiles$admin_level[id])

# Mean rates by location for whole period
tot_rates <- chol_gen$summary(variables = "location_total_rates_output", 
                              c(posterior::default_summary_measures(),
                                posterior::default_convergence_measures()),
                              .cores = 4) %>% 
  mutate(id = str_extract(variable, "[0-9]+") %>% as.numeric(),
         location_period_id = output_shapefiles$location_period_id[id],
         shapeName = output_shapefiles$shapeName[id],
         admin_level = output_shapefiles$admin_level[id])
```
### Figures
```{r out-cases}
#| fig.height=5,
#| fig.width=10,
#| fig.cap=capFig("Mean cases per year")

output_data %>% 
  ggplot(aes(fill = log10(cases))) +
  geom_sf(col = "white", size = .05) +
  facet_grid(admin_level ~ TL) +
  scale_fill_viridis_c() +
  ggthemes::theme_map() +
  theme(legend.position = "right")

```

```{r out-rates}
#| fig.height=5,
#| fig.width=10,
#| fig.cap=capFig("Mean rate per year")

output_data %>% 
  ggplot(aes(fill = log10(rate))) +
  geom_sf(col = "white", size = .05) +
  facet_grid(admin_level ~ TL) +
  scale_fill_viridis_c() +
  ggthemes::theme_map() +
  theme(legend.position = "right")

```


```{r risk_prop}
#| fig.height=5,
#| fig.width=10,
#| fig.cap=capFig("Proportion per risk category (per 100'000)")

risk_cat_dict <- c("<1", "1-10", "10-100", ">100")

risk_cat_pop <- chol_gen$summary(variables = "location_risk_cat_prop", .cores = 6) %>% 
  mutate(id = str_extract(variable, "(?<=\\[)[0-9]+") %>% as.numeric(),
         risk_cat = str_extract(variable, "(?<=,)[0-9]+") %>% as.numeric(),
         risk_cat = factor(risk_cat_dict[risk_cat], levels = risk_cat_dict),
         location_period_id = output_shapefiles$location_period_id[id],
         admin_level = str_extract(location_period_id, "ADM[0-2]")) %>% 
  inner_join(output_shapefiles, ., by = c("location_period_id", "admin_level"))


risk_cat_pop %>% 
  ggplot(aes(fill = median)) +
  geom_sf(col = "white", size = .05) +
  facet_grid(admin_level ~ risk_cat) +
  scale_fill_viridis_c() +
  ggthemes::theme_map() +
  theme(legend.position = "right")

```

```{r risk_num}
#| fig.height=5,
#| fig.width=10,
#| fig.cap=capFig("Number per risk category  (per 100'000)")

risk_cat_dict <- c("<1", "1-10", "10-100", ">100")

risk_cat_num <- chol_gen$summary(variables = "location_risk_cat_num", .cores = 6) %>% 
  mutate(id = str_extract(variable, "(?<=\\[)[0-9]+") %>% as.numeric(),
         risk_cat = str_extract(variable, "(?<=,)[0-9]+") %>% as.numeric(),
         risk_cat = factor(risk_cat_dict[risk_cat], levels = risk_cat_dict),
         location_period_id = output_shapefiles$location_period_id[id],
         admin_level = str_extract(location_period_id, "ADM[0-2]")) %>% 
  inner_join(output_shapefiles, ., by = c("location_period_id", "admin_level"))


risk_cat_num %>% 
  ggplot(aes(fill = log10(median))) +
  geom_sf(col = "white", size = .05) +
  facet_grid(admin_level ~ risk_cat) +
  scale_fill_viridis_c() +
  ggthemes::theme_map() +
  theme(legend.position = "right")

```

### Tables

*Cases by location and year*:
```{r out-table-cases}

cases_summ <- output_data %>%
  st_drop_geometry() %>% 
  dplyr::select(shapeName, admin_level, TL, contains("cases")) %>% 
  mutate(TL = as.character(lubridate::year(TL))) %>% 
  bind_rows(tot_cases %>% 
              rename(cases = mean,
                     cases_q5 = q5,
                     cases_q95 = q95) %>% 
              dplyr::select(shapeName, admin_level, contains("cases")) %>% 
              mutate(TL = "Total")) %>% 
  mutate(text = str_c(
    round(cases), " (",
    round(cases_q5), "-", 
    round(cases_q95), ")"
  )) %>% 
  dplyr::select(shapeName, admin_level, TL, text) %>% 
  pivot_wider(values_from = "text",
              names_from = "TL") %>% 
  arrange(admin_level, shapeName)

cases_summ %>% 
  dplyr::select(-admin_level) %>% 
  kableExtra::kbl(caption = "Cases by location and year") %>% 
  kableExtra::kable_styling(full_width = FALSE) %>% 
  kableExtra::pack_rows(index = table(cases_summ$admin_level))

```


*Rates by location and year*:
```{r out-table-rates}
rate_multiplier <- 1e4

rates_summ <- output_data %>%
  st_drop_geometry() %>% 
  dplyr::select(shapeName, admin_level, TL, contains("rate")) %>% 
  mutate(TL = as.character(lubridate::year(TL))) %>% 
  bind_rows(tot_rates %>% 
              rename(rate = mean,
                     rate_q5 = q5,
                     rate_q95 = q95) %>% 
              dplyr::select(shapeName, admin_level, contains("rate")) %>% 
              mutate(TL = "Total")) %>% 
  mutate(text = str_c(
    (rate * rate_multiplier) %>% formatC(digits = 1, big.mark = "'", format = "f"), " (",
    (rate_q5 * rate_multiplier) %>% formatC(digits = 1, big.mark = "'", format = "f"), "-", 
    (rate_q95 * rate_multiplier) %>% formatC(digits = 1, big.mark = "'", format = "f"), ")"
  )) %>% 
  dplyr::select(shapeName, admin_level, TL, text) %>% 
  pivot_wider(values_from = "text",
              names_from = "TL") %>% 
  arrange(admin_level, shapeName)

rates_summ %>% 
  dplyr::select(-admin_level) %>% 
  kableExtra::kbl(caption = "Cases per 10'000 people by location and year") %>% 
  kableExtra::kable_styling(full_width = FALSE) %>% 
  kableExtra::pack_rows(index = table(cases_summ$admin_level))

```
