---
title: "Data and Model Outputs Report"
output: html_document
params:
  config: "~/git/cholera-configs/summary_parameters.csv"
  cholera_configs_directory: "~/git/cholera-configs"
  cholera_mapping_pipeline_directory: "~/git/cholera-mapping-pipeline"
---
```{r setup, include=FALSE, dev="CairoPNG"}
knitr::opts_chunk$set(
  echo = FALSE,
  dev="CairoPNG",
  fig.align = "center"
  )
library(taxdat)
```

# Loading Config

```{r Load config}
  config <- read.csv(params$config)

  all_countries <- unique(config[["Country.Name"]])
```

We considered data from `r paste(all_countries, collapse = ', ')`.

```{r Load Populations}
  data(codelist, package = "countrycode")
  data(pop, package = "wpp2019")
  library(magrittr)
  country_cw <- dplyr::select(codelist, iso3n, iso3c) %>% 
  dplyr::filter(!is.na(iso3n) & !is.na(iso3c))
  pop <- pop[,c("country_code", "name", "2015", "2020")] ## get 2015 & 2020 estimates only
  names(pop) <- c("iso3n", "country", "p2015", "p2020")
  popdf <- dplyr::inner_join(country_cw, pop, by = c("iso3n")) %>%
    dplyr::mutate(pop = rowMeans(cbind(p2015, p2020), na.rm = TRUE)*1000) %>% ## mean of 2015 & 2020 pop estimates
    dplyr::select(iso3c, pop)

  pop_by_country <- setNames(popdf[["pop"]], popdf[["iso3c"]])

  print("Using 2020 populations pulled from the wpp2019 package")
  
```

```{r Load Data}
  all_data <- list(Cases = list(), Rates = list())
  for (country in config[["Country.Name"]]) {
    local_config <- config[config[["Country.Name"]] == country, ]
    if (local_config[["Include"]] == "MultiYearModel") {
      config <- yaml::read_yaml(paste0(params$cholera_configs_directory, "/2015_2019_full_base/", country, ".yml"))
      filenames <- taxdat::get_filenames(config, cholera_directory = params$cholera_mapping_pipeline_directory)
      full_output <- taxdat::read_file_of_type(filenames[["stan_output"]], "model.rand")
      mean_output <-  MCMCvis::MCMCsummary(full_output, params = "grid_cases", func = mean)
      if (local_config[["Data"]] == "full") {
        all_data[["Cases"]][[country]] <- sum(mean_output[["mean"]]) / (2019 - 2015 + 1)
        cat(paste("Cases for country,", country, "are", sum(mean_output[["mean"]], na.rm=TRUE)))
      } else if (local_config[["Data"]] == "non-empty"){
        all_years <- 2015:2019
        used_years <- 2015 + sort(unique(stan_input$stan_data$map_grid_time[stan_input$stan_data$map_loc_grid_grid])) - 1
        all_data[["Cases"]][[country]] <- sum(mean_output[["mean"]][unique(map_loc_grid_grid)]) / (length(used_years))
      }
      all_data[["Rates"]][[country]] <- all_data[["Cases"]][[country]] / pop_by_country[[country]]
    } else if (local_config[["Include"]] == "SingleYearModels") {
      years <- strsplit(split=':', local_config[["Data"]])[[1]]
      all_data[["Cases"]][[country]] <- c()
      for (year in years) {
        config <- yaml::read_yaml(paste0(params$cholera_configs_directory, "/single_year_configs/1cov/",year,"_poisson_big_1cov/config_", country, "_", year, "_", year, ".yml"))
        filenames <- taxdat::get_filenames(config = config, cholera_directory = params$cholera_mapping_pipeline_directory)
        full_output <- taxdat::read_file_of_type(filenames[["stan_output"]], "model.rand")
        mean_output <-  MCMCvis::MCMCsummary(full_output, params = "grid_cases", func = mean)
        all_data[["Cases"]][[country]][as.character(year)] <- sum(mean_output[["mean"]], na.rm = TRUE)
      }
      all_data[["Cases"]][[country]] <- mean(all_data[["Cases"]][[country]])
      cat(paste("Cases for country,", country, "are", mean(all_data[["Cases"]][[country]])))
    } else if (local_config[["Include"]] == "Lancet") {
      stop("This code is not yet written")
    } else if (local_config[["Include"]] == "None") {
    } else {
      stop(paste("Unknown include type", local_config[["Include"]], "permitted types are (MultiYearModel, SingleYearModel, Lancet, and None)"))
    }
  
    
  }
```
