name: MRT
aoi: raw
countries: '681'
countries_name: MRT
start_time: '2010-01-01'
end_time: '2016-12-31'
res_time: 1 years
res_space: 20
smoothing_period: 1
case_definition: suspected
covariate_choices:
- dist_to_water
- water_access
- san_access
- open_defe
- stunting
- wasting
- access_cities
data_source: sql
ovrt_metadata_table: no
ingest_covariates: no
ingest_new_covariates: no
censoring: yes
aggregate: yes
time_effect: yes
time_effect_autocorr: no
use_weights: no
overdispersion: 8.0
stan:
  ncores: 4
  model: update_yearly_dagar_timevary_speedup_flexible_negbinom_rates_fixedphi.stan
  niter: 2000
  recompile: yes
