general:
  location_name: AFR::KEN
  start_date: '2000-01-01'
  end_date: '2001-12-31'
  width_in_km: 20.0
  height_in_km: 20.0
  time_scale: year
stan:
  directory: /home/jkaminsky/git/cholera-mapping-pipeline/Analysis/Stan
  ncores: 2.0
  model: dagar_seasonal_flexible.stan
  niter: 10000.0
  recompile: yes
name: test_real_edition
case_definition: suspected
covariate_choices: ~
data_source: sql
file_names:
  stan_output: /home/jkaminsky/git/cholera-mapping-pipeline/Analysis/output/test.stan_output.rdata
  stan_input: /home/jkaminsky/git/cholera-mapping-pipeline/Analysis/output/test.stan_input.rdata
processing:
initial_values:
  warmup: no