general:
  location_name: '1'
  start_date: '2000-01-01'
  end_date: '2001-12-31'
  width_in_km: 1.0
  height_in_km: 1.0
  time_scale: year
stan:
  directory: /home/app/cmp/Analysis/Stan
  ncores: 1.0
  model: dagar_seasonal.stan
  niter: 10000.0
  recompile: yes
name: test_???
taxonomy: taxonomy-working/working-entry1
smoothing_period: 1.0
case_definition: suspected
covariate_choices: ~
data_source: sql
file_names:
  stan_output: /home/app/cmp/Analysis/output/test5.stan_output.rdata
  stan_input: /home/app/cmp/Analysis/output/test5.stan_input.rdata
nrows: 10.0
ncols: 10.0
data_type: Grid data
oc_type: Inconsistent observations over spatial levels (2 times difference) and Partial
  coverage without missing data
polygon_type: Fake polygon
grid_coverage_type: 100%
randomize: yes
ncovariates: 2.0
single_year_run: no
iteration: 10000.0
nonspatial:
- no
- no
- no
nontemporal:
- no
- no
- no
spatially_smooth:
- yes
- yes
- no
temporally_smooth:
- no
- no
- no
polygonal:
- yes
- yes
- yes
radiating:
- no
- no
- yes
constant:
- yes
- no
- no
Data_simulation_covariates:
- yes
- yes
- yes
Model_covariates:
- yes
- yes
- no
