general:
  location_name: '1'
  start_date: '2000-01-01'
  end_date: '2001-12-31'
  width_in_km: 1.0
  height_in_km: 1.0
  time_scale: year
stan:
  directory: /home/app/cmp/Analysis/Stan
  ncores: 1.0
  model: dagar_seasonal.stan
  niter: 1000.0
  recompile: yes
name: test_???
taxonomy: taxonomy-working/working-entry1
smoothing_period: 1.0
case_definition: suspected
covariate_choices: ~
data_source: sql
file_names:
  stan_output: /home/app/cmp/Analysis/output/test3.stan_output.rdata
  stan_input: /home/app/cmp/Analysis/output/test3.stan_input.rdata
nrows: 10.0
ncols: 10.0
data_type: Grid data
oc_type: '-'
polygon_type: Fake polygon
polygon_coverage: 100%
randomize: yes
ncovariates: 3.0
single_year_run: 'no'
iteration: 1000.0
nonspatial:
- no
- no
- no
nontemporal:
- yes
- yes
- yes
spatially_smooth:
- yes
- yes
- yes
temporally_smooth:
- no
- no
- no
polygonal:
- yes
- yes
- yes
radiating:
- no
- no
- yes
constant:
- yes
- no
- no
Data_simulation_covariates:
- yes
- yes
- yes
Model_covariates:
- yes
- yes
- no
Observations_with_inconsistent_data: '*0.5'
Loc_with_inconsistent_data:
- 1::89
- 1::14
- 1:99
Cov_data_simulation_filename: /home/app/cmp/Analysis/output/test_case_3_data_simulation_covariates.rdata
