general:
  location_name: '1'
  start_date: '2000-01-01'
  end_date: '2001-12-31'
  width_in_km: 2.0
  height_in_km: 2.0
  time_scale: year
stan:
  directory: /home/app/test/Analysis/Stan
  ncores: 1.0
  model: dagar_seasonal_flexible.stan
  niter: 10000.0
  recompile: yes
name: test_???
taxonomy: taxonomy-working/working-entry1
smoothing_period: 1.0
case_definition: suspected
covariate_choices: ~
data_source: sql
file_names:
  stan_output: /home/app/test/Analysis/output/test.stan_output.rdata
  stan_input: /home/app/test/Analysis/output/test.stan_input.rdata
processing:
  aggregate: yes
  remove_overlaps: yes
