
# install.packages("packages/taxdat", type="source", repos=NULL)
library(readr)

#========================================================READ ME========================================================#
# This new config writer is updated for the Dec 2021 run on 10/26/2021
# This new writer only works as supposed to with the updated "auto_config_Dec2021" function in the config_helpers.R 
# Please pull that change as well, and then reinstall the taxdat package before generating configs
# This script can be run separately using the 'Rscript' or '/opt/R/4.0.3/bin/Rscript' command
# Before the run, this script can be put anywhere, but YOU HAVE TO MODIFY THE CURRENT WORKING DIRECTORY FIRST 
# The created config files will be stored in 'Analysis/configs/Dec_2021_runs/'  
# All the changes made on top of the configs generated by this writer may be recorded on GitHub                                             
#========================================================READ ME========================================================#  
working_directory <- "/home/kaiyuezou/mapping_pipeline/9_23_dev/cholera-mapping-pipeline/" #<--------CHANGE THIS AND KEEP BOTH "//" ON BOTH SIDES
setwd(working_directory)
config_path <- "Analysis/configs/Dec_2021_runs"
dir.create(file.path(working_directory, config_path), FALSE)



#### Modify the following settings      ############## no need for changes for the Dec 2021 runs
#### to generate one config per country ##############

scale <- "country" ## country or region maps
# covar_names <- c("dist_to_water", "water_access", "san_access", "open_defe", "stunting", "wasting", "access_cities")
covar_names <- c("dist_to_water")

ids <- read_csv("Analysis/R/locations_todeletelater.csv") # location ids
cw <- read_csv("Analysis/R/region_country.csv")
locs <- dplyr::right_join(cw, ids, by = c("country" = "region")) ## region & country grouping

## rm later
locs <- dplyr::filter(locs, !is.na(region))

config_start_time <- Sys.getenv("CHOLERA_START_TIME","2015-01-01")
config_end_time <- Sys.getenv("CHOLERA_END_TIME","2019-12-31")

params_df <- data.frame(
    OCs = '', 
    aoi = "raw",
    res_space = 20,
    res_time = '1 years',
    smoothing_period = 1,
    case_definition = 'suspected',
    start_time = config_start_time,
    end_time = config_end_time,
    data_source = 'sql',
    ingest_covariates = 'no',
    warmup = 'yes',
    covar_warmup = 'yes',
    censoring = 'no',
    aggregate = 'yes',
    use_weights = 'no', 
    time_effect = 'yes',
    time_effect_autocorr = 'no',
    beta_sigma_scale = 1.0,
    sigma_eta_scale = 5.0,
    ncores = 4,
    model = 'update_yearly_dagar_timevary_speedup_flexible',
    
    niter = 2000,
    recompile = TRUE
              )

rm(config_start_time, config_end_time)
##############################################
par <- params_df[1,]
start_year <- lubridate::year(as.Date(par$start_time))
end_year <- lubridate::year(as.Date(par$end_time))

if(scale == "region"){

  regions <- unique(locs$region)
  for (i in 1:length(regions)){
    ctry_names <- locs[which(locs$region == regions[i]),]$country
    ctry_ids <- locs[which(locs$region == regions[i]),]$id
    config_path2 <- paste0(config_path, "/", start_year, "_", end_year, "_region")
    dir.create(config_path2, showWarnings = FALSE)

    config_fname <- paste0(config_path2, "/config_", regions[i], "_", start_year, "_", end_year, ".yml")
    sink(file = config_fname)
    taxdat::automate_mapping_config(par, covar_names, ctry_names, ctry_ids)
    sink()

  }

} else if (scale == "country"){

  for (j in 1:nrow(locs)){
    ctry_name <- locs[j,]$country
    ctry_id <- locs[j,]$id
    config_path2 <- paste0(config_path, "/", start_year, "_", end_year, "_country")
    dir.create(config_path2, showWarnings = FALSE)

    config_fname <- paste0(config_path2, "/config_", ctry_name, "_", start_year, "_", end_year, ".yml")
    sink(file = config_fname)
    taxdat::auto_config_Dec2021(par, covar_names, ctry_name, ctry_id)
    sink()
  }

} else {
  stop(paste("Writing configs at", scale, "scale is not yet implemented."))
}






