name: unit-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    container:
      image: docker://hopkinsidd/choleramappingpipeline:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Layers
        uses: actions/checkout@v2
        with:
          repository: https://github.com/HopkinsIDD/cholera-covariates.git
          path: Layers/
          lfs: true
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Set up Rprofile
        run: cp Docker.Rprofile $HOME/.Rprofile
        shell: bash
      - name: Run taxdat tests
        run: |
          setwd("packages/taxdat")
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
      - name: Run integration tests
        env: 
          CHOLERA_API_USERNAME: ${{ secrets.CHOLERA_API_USERNAME }}
          CHOLERA_API_KEY: ${{ secrets.CHOLERA_API_KEY }}
        run: |
          git clone git@github.com:HopkinsIDD/cholera-covariates.git Layers
          service postgresql start
          bash grant_cholera_database.sh root
          Rscript -e "install.packages('packages/taxdat',type='source',repos=NULL)"
          export USER=root
          cd test
          Rscript run_tests.R
        shell: bash

