name: unit-tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    container:
      image: docker://hopkinsidd/choleramappingpipeline:latest-dev
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Analysis/configs
        uses: actions/checkout@v2
        with:
          repository: HopkinsIDD/cholera-configs
          path: Analysis/configs/
          lfs: false
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Checkout Layers
        uses: actions/checkout@v2
        with:
          repository: HopkinsIDD/cholera-covariates
          ref: for_testing
          path: Layers/
          lfs: true
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Set up Rprofile
        run: cp Docker.Rprofile $HOME/.Rprofile
        shell: bash
      - name: Run taxdat tests
        run: |
          setwd("packages/taxdat")
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
      - name: Run integration tests
        env:
          CHOLERA_API_USERNAME: ${{ secrets.CHOLERA_API_USERNAME }}
          CHOLERA_API_KEY: ${{ secrets.CHOLERA_API_KEY }}
        run: |
          service postgresql start
          bash grant_cholera_database.sh root
          export USER=root
          Rscript -e "install.packages('packages/taxdat',type='source',repos=NULL)"
          echo "Rscript ~/Analysis/R/prepare_grid_cmd.R -d ./ -u root -r 1 -i TRUE"
          Rscript ~/Analysis/R/prepare_grid_cmd.R -d Layers/ -u root -r 1 -i TRUE
          echo "Rscript ~/Analysis/R/prepare_covariates_cmd.R -d cholera-covariates/ -u root -r 1 -t '1 years' -i TRUE -p FALSE -n 1 -o TRUE -x FALSE -m TRUE -c p -g 'public.grid_1_1' -a ken"
          Rscript ~/Analysis/R/prepare_covariates_cmd.R -d cholera-covariates/ -u root -r 1 -t '1 years' -i TRUE -p FALSE -n 1 -o TRUE -x FALSE -m TRUE -c p -g 'public.grid_1_1' -a ken
          cd test
          Rscript run_tests.R
        shell: bash
