name: unit-tests

on:
  push:
    branches:
      - master
      - dev
      - new_pipeline
  pull_request:
    branches:
      - master
      - dev
      - new_pipeline

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    container:
      image: docker://hopkinsidd/choleramappingpipeline:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Analysis/configs
        uses: actions/checkout@v2
        with:
          repository: HopkinsIDD/cholera-configs
          path: Analysis/configs/
          lfs: false
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Checkout Layers
        uses: actions/checkout@v2
        with:
          repository: HopkinsIDD/cholera-covariates
          ref: for_testing
          path: Layers/
          lfs: true
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Set up Rprofile
        run: cp Docker.Rprofile $HOME/.Rprofile
        shell: bash
      - name: Run taxdat tests
        run: |
          setwd("packages/taxdat")
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
      - name: Run integration tests (new)
        env:
          CHOLERA_API_USERNAME: ${{ secrets.CHOLERA_API_USERNAME }}
          CHOLERA_API_KEY: ${{ secrets.CHOLERA_API_KEY }}
        run: |
          service postgresql start
          bash grant_cholera_database.sh root
          export USER=root
          Rscript -e "install.packages('packages/taxdat',type='source',repos=NULL)"
          cd tests
          Rscript -e "testthat::test_dir('./', stop_on_failure=TRUE)"
        shell: bash
