# This workflow will build and push a new container image to Amazon ECR
# The following information will need to be included in your Github secrets:
# - DOCKER_USERNAME: docker user name
# - DOCKER_PASSWORD: password or access token

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'packages/**'
      - '.Rprofile'
      - 'packrat/**'

name: Deploy to DockerHub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        Username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Tags
      id: tags
      env:
        IMAGE_TAG_RUN: ${{ github.run_number }}
        IMAGE_TAG_REF: ${{ github.ref }}
      run: |
        echo "::set-output name=shashort::$(git log -1 --pretty=%h)"
        echo "::set-output name=reftag::${IMAGE_TAG_REF##*/}-r$IMAGE_TAG_RUN"

    - name: Build Push Master
      uses: docker/build-push-action@v2
      with:
        tags: |
          hopkinsidd/covidscenariopipeline:latest
          hopkinsidd/covidscenariopipeline:latest-master
          hopkinsidd/covidscenariopipeline:${{steps.tags.outputs.shashort}}
          hopkinsidd/covidscenariopipeline:${{steps.tags.outputs.reftag}}
          hopkinsidd/covidscenariopipeline:${{ github.sha }}
