# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: [".github/workflows/style.yml", "**.[rR]", "**.[rR]md", "**.[rR]markdown", "**.[rR]nw"]
  pull_request:
    paths: [".github/workflows/style.yml", "**.[rR]", "**.[rR]md", "**.[rR]markdown", "**.[rR]nw"]

name: Style

jobs:
  style:
    runs-on: ubuntu-20.04
    container:
      image: docker://hopkinsidd/choleramappingpipeline:latest-dev
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: false
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0
      - name: Set up Rprofile
        run: |
          cp Docker.Rprofile $HOME/.Rprofile
          cp -R /home/app/.cache $HOME/.cache
          pwd
          ls
          git config --global --add safe.directory .
          git status
          exit 1
        shell: bash

      - name: Setup styler
        run: install.packages('styler', repos = c('http://cran.r-project.org/'))
        shell: Rscript {0}
      - name: Enable styler cache
        run: styler::cache_activate()
        shell: Rscript {0}

      - name: Determine cache location
        id: styler-location
        run: |
          cat(
            "##[set-output name=location;]",
            styler::cache_info(format = "tabular")$location,
            "\n",
            sep = ""
          )
        shell: Rscript {0}

      - name: Cache styler
        uses: actions/cache@v2
        with:
          path: ${{ steps.styler-location.outputs.location }}
          key: ${{ runner.os }}-styler-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-styler-
            ${{ runner.os }}-
      - name: Style
        run: styler::style_dir(".", exclude_dirs = c("renv", "renv.cache"), filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"))
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '.'
